import React, { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ChevronLeft, ChevronRight, Search } from 'lucide-react';
import { fetchFundingActivity, fetchMetaAdAccounts, reviewFundingSession } from '../../lib/api';
import { SessionDrawer } from './SessionDrawer';

const money=(v:any)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v||0)/100);
const label=(v:any)=>String(v||'Unknown').toLowerCase().replaceAll('_',' ');
const msg=(e:any)=>e?.response?.data?.message||e?.message||'Request failed';
export const ActivityView:React.FC<{reviewOnly?:boolean}>=({reviewOnly=false})=>{
 const qc=useQueryClient(); const [page,setPage]=useState(1); const [selected,setSelected]=useState<string|null>(null); const [search,setSearch]=useState(''); const [debounced,setDebounced]=useState(''); const [status,setStatus]=useState(''); const [accountId,setAccountId]=useState(''); const [source,setSource]=useState(''); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [review,setReview]=useState<{id:string;decision:'CONFIRM'|'REJECT'}|null>(null); const [reason,setReason]=useState('');
 useEffect(()=>{const t=setTimeout(()=>setDebounced(search.trim()),250);return()=>clearTimeout(t)},[search]);
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setReview(null);setSelected(null)}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 useEffect(()=>setPage(1),[debounced,status,accountId,source,from,to,reviewOnly]);
 const query={page,pageSize:25,search:debounced||undefined,status:status||undefined,accountId:accountId||undefined,source:source||undefined,from:from||undefined,to:to||undefined,readyForReview:reviewOnly?'true' as const:undefined};
 const data=useQuery({queryKey:['funding-activity',query],queryFn:()=>fetchFundingActivity(query)}); const accounts=useQuery({queryKey:['meta-accounts'],queryFn:()=>fetchMetaAdAccounts()});
 const act=useMutation({mutationFn:()=>reviewFundingSession(review!.id,review!.decision,reason||undefined),onSuccess:async()=>{await qc.invalidateQueries({queryKey:['funding-activity']});setReview(null);setReason('')}});
 const items=data.data?.items||[]; const total=data.data?.total||0; const pages=Math.max(1,Math.ceil(total/25));
 return <><div className="funding-panel"><div className="funding-toolbar"><div className="relative min-w-[210px] flex-1 max-w-sm"><Search className="absolute left-2.5 top-2.5 w-3.5 h-3.5 text-[#657383]"/><input className="funding-input w-full pl-8" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search account or session"/></div><select className="funding-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All operational states</option>{['MAPPED','UI_OBSERVED','REVIEW_REQUIRED','CANCELLED','EXPIRED'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><select className="funding-input" value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">All accounts</option>{(accounts.data||[]).map((a:any)=><option value={a.id} key={a.id}>{a.name}</option>)}</select><select className="funding-input" value={source} onChange={e=>setSource(e.target.value)}><option value="">All sources</option><option value="FUNDING_REQUEST">Funding request</option><option value="FUND_LOT">Direct Fund Lot</option></select><input aria-label="From date" title="From date" type="date" className="funding-input" value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="To date" title="To date" type="date" className="funding-input" value={to} onChange={e=>setTo(e.target.value)}/></div>
 {data.error&&<div className="p-3 text-xs text-rose-700 bg-rose-50">{msg(data.error)}</div>}{data.isFetching&&!data.data?<div className="funding-empty">Loading observations...</div>:!items.length?<div className="funding-empty">{reviewOnly?'No observations need finance review.':'No observations match these filters.'}</div>:<div className="funding-table-wrap"><table className="funding-table"><thead><tr><th>Account</th><th>Amount</th><th>Source</th><th>Evidence</th><th>Operational</th><th>Financial review</th><th>Operator / device</th><th>Observed</th><th></th></tr></thead><tbody>{items.map((s:any)=>{const mismatch=s.detectedAdAccountId&&s.selectedAdAccountId&&s.detectedAdAccountId!==s.selectedAdAccountId; return <tr key={s.id}><td><div className="font-semibold">{s.selectedAdAccount?.name||'Unknown account'}</div><div className="funding-muted">{s.selectedAdAccount?.metaAdAccountId||s.selectedAdAccountId}</div></td><td className="funding-number font-semibold">{money(s.selectedAmountMinor)}</td><td>{s.fundingRequestId?'Funding request':'Direct Fund Lot'}</td><td><div>{label(s.confidence)} confidence</div><div className={`funding-muted ${mismatch?'text-rose-700':''}`}>{mismatch?'Account mismatch':'Account aligned'}</div></td><td><span className={`funding-status ${s.operationalState==='UI_OBSERVED'?'good':s.operationalState==='REVIEW_REQUIRED'?'bad':'warn'}`}>{label(s.operationalState)}</span></td><td>{label(s.financialReviewState)}</td><td><div>{s.actorUserId}</div><div className="funding-muted">{s.extensionDeviceId||'Web session'}</div></td><td>{new Date(s.uiObservedAt||s.createdAt).toLocaleString()}</td><td className="whitespace-nowrap"><button className="meta-btn-secondary mr-1" onClick={()=>setSelected(s.id)}>Details</button>{reviewOnly&&<><button className="meta-btn-primary mr-1" onClick={()=>setReview({id:s.id,decision:'CONFIRM'})}>Confirm</button><button className="meta-btn-ghost text-rose-700" onClick={()=>setReview({id:s.id,decision:'REJECT'})}>Reject</button></>}</td></tr>})}</tbody></table></div>}
 <div className="funding-toolbar border-t border-[#e4e7eb] border-b-0"><span className="funding-muted mr-auto">Showing {items.length?((page-1)*25)+1:0}–{Math.min(page*25,total)} of {total}</span><button disabled={page<=1} className="meta-btn-secondary" onClick={()=>setPage(p=>p-1)} title="Previous page"><ChevronLeft className="w-3.5 h-3.5"/></button><span className="text-xs">Page {page} of {pages}</span><button disabled={page>=pages} className="meta-btn-secondary" onClick={()=>setPage(p=>p+1)} title="Next page"><ChevronRight className="w-3.5 h-3.5"/></button></div></div>
 {selected&&<SessionDrawer id={selected} onClose={()=>setSelected(null)}/>} {review&&<div className="funding-overlay"><form className="funding-dialog" onSubmit={e=>{e.preventDefault();act.mutate()}}><div className="p-4 border-b border-[#e4e7eb]"><div className="font-semibold">{review.decision==='CONFIRM'?'Confirm observation':'Reject observation'}</div><div className="funding-muted mt-1">This updates review and reservation status only. No ledger entry will be posted.</div></div><div className="p-4"><label className="text-xs font-semibold">Reason {review.decision==='REJECT'?'(required)':'(optional)'}<textarea required={review.decision==='REJECT'} maxLength={240} className="funding-input w-full mt-1 min-h-20 py-2" value={reason} onChange={e=>setReason(e.target.value)}/></label>{act.error&&<div className="text-xs text-rose-700 mt-2">{msg(act.error)}</div>}</div><div className="p-3 border-t border-[#e4e7eb] flex justify-end gap-2"><button type="button" className="meta-btn-secondary" onClick={()=>setReview(null)}>Cancel</button><button className={review.decision==='CONFIRM'?'meta-btn-primary':'meta-btn-secondary text-rose-700'} disabled={act.isPending}>{act.isPending?'Saving...':review.decision==='CONFIRM'?'Confirm review':'Reject observation'}</button></div></form></div>}</>;
};
