import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ChevronDown, Copy, Download, Link2, Trash2 } from 'lucide-react';
import { createExtensionPairing, fetchExtensionDevices, revokeExtensionDevice } from '../../lib/api';

const message = (error:any) => error?.response?.data?.message || error?.message || 'Request failed';
export const DevicesView: React.FC = () => {
  const qc=useQueryClient(); const [pairing,setPairing]=useState<any>(null); const [showInstall,setShowInstall]=useState(false);
  const devices=useQuery({queryKey:['funding-devices'],queryFn:fetchExtensionDevices,refetchInterval:30000});
  const pair=useMutation({mutationFn:createExtensionPairing,onSuccess:setPairing});
  const revoke=useMutation({mutationFn:revokeExtensionDevice,onSuccess:()=>qc.invalidateQueries({queryKey:['funding-devices']})});
  return <div className="funding-panel"><div className="funding-toolbar"><div className="mr-auto"><div className="font-semibold">Extension devices</div><div className="funding-muted">Active browsers renew automatically for 30 days. Revoke any device you no longer use.</div></div><a className="meta-btn-secondary flex items-center gap-1.5" href="/downloads/ads-control-companion-v1.0.9.zip" download><Download className="w-3.5 h-3.5"/>Download extension</a><button className="meta-btn-primary flex items-center gap-1.5" onClick={()=>pair.mutate()}><Link2 className="w-3.5 h-3.5"/>Generate pairing code</button></div>
    <button className="funding-install-toggle" onClick={()=>setShowInstall(value=>!value)} aria-expanded={showInstall}><span>Chrome installation steps</span><ChevronDown className={`w-4 h-4 transition-transform ${showInstall?'rotate-180':''}`}/></button>
    {showInstall&&<ol className="funding-install-steps"><li>Download and extract the ZIP file.</li><li>Open <code>chrome://extensions</code> and enable Developer mode.</li><li>Select <strong>Load unpacked</strong> and choose the extracted folder.</li><li>Generate a pairing code here, click the extension icon in Chrome, and paste the code.</li></ol>}
    {pairing&&<div className="m-3 p-3 bg-blue-50 border border-blue-200 rounded-[5px] flex flex-wrap items-center gap-3"><div className="mr-auto"><div className="text-xs font-semibold">One-time pairing code</div><div className="funding-muted">Expires {new Date(pairing.expiresAt).toLocaleString()}. It cannot be shown again after claim.</div></div><code className="text-lg font-semibold tracking-widest">{pairing.code}</code><button className="meta-btn-secondary" onClick={()=>navigator.clipboard.writeText(pairing.code)} title="Copy pairing code"><Copy className="w-3.5 h-3.5"/></button></div>}
    {(devices.error||pair.error||revoke.error)&&<div className="p-3 text-xs text-rose-700 bg-rose-50">{message(devices.error||pair.error||revoke.error)}</div>}
    {devices.isLoading?<div className="funding-empty">Loading devices...</div>:!devices.data?.length?<div className="funding-empty">No extension device has been paired.</div>:<div className="funding-table-wrap"><table className="funding-table"><thead><tr><th>Device</th><th>Version</th><th>Status</th><th>Last seen</th><th>Credential expiry</th><th></th></tr></thead><tbody>{devices.data.map((d:any)=>{const revoked=Boolean(d.revokedAt); const expired=new Date(d.expiresAt)<new Date(); return <tr key={d.id}><td><div className="font-semibold">{d.name}</div><div className="funding-muted">{d.id}</div></td><td>{d.version}</td><td><span className={`funding-status ${revoked||expired?'bad':'good'}`}>{revoked?'Revoked':expired?'Expired':'Active'}</span></td><td>{d.lastSeenAt?new Date(d.lastSeenAt).toLocaleString():'Never'}</td><td>{new Date(d.expiresAt).toLocaleString()}</td><td className="text-right">{!revoked&&<button title="Revoke device" className="meta-btn-ghost" onClick={()=>revoke.mutate(d.id)}><Trash2 className="w-3.5 h-3.5"/></button>}</td></tr>})}</tbody></table></div>}
  </div>;
};
