import React, { useEffect } from 'react';
import { useQuery } from '@tanstack/react-query';
import { X } from 'lucide-react';
import { fetchFundingSession } from '../../lib/api';

const money=(v:any)=>v==null?'Not detected':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v)/100);
const label=(v:any)=>String(v||'Unknown').toLowerCase().replaceAll('_',' ');
export const SessionDrawer:React.FC<{id:string;onClose:()=>void}>=({id,onClose})=>{
 const q=useQuery({queryKey:['funding-session',id],queryFn:()=>fetchFundingSession(id)}); const s=q.data;
 useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[onClose]);
 return <><div className="fixed inset-0 z-[65] bg-black/30" onClick={onClose}/><aside className="funding-drawer" role="dialog" aria-modal="true" aria-label="Top-up session details"><div className="sticky top-0 bg-white p-4 border-b border-[#e4e7eb] flex justify-between z-10"><div><div className="font-semibold">Observation details</div><div className="funding-muted">Session {id}</div></div><button onClick={onClose} aria-label="Close"><X className="w-4 h-4"/></button></div>
 {q.isLoading?<div className="funding-empty">Loading timeline...</div>:q.error?<div className="p-4 text-xs text-rose-700">Could not load this session.</div>:<div className="p-4 space-y-5">
  <section><h3 className="text-xs font-semibold mb-2">Payment evidence</h3><dl className="grid grid-cols-2 gap-x-4 gap-y-2 text-xs"><div><dt className="funding-muted">Detected amount</dt><dd className="funding-number font-semibold">{money(s.detectedAmountMinor)}</dd></div><div><dt className="funding-muted">Selected amount</dt><dd className="funding-number font-semibold">{money(s.selectedAmountMinor)}</dd></div><div><dt className="funding-muted">Detected Meta account</dt><dd>{s.detectedMetaAccountId||'Not detected'}</dd></div><div><dt className="funding-muted">Selected account</dt><dd>{s.selectedAdAccount?.name||s.selectedAdAccountId||'None'}</dd></div><div><dt className="funding-muted">Confidence</dt><dd>{label(s.confidence)}</dd></div><div><dt className="funding-muted">Detector</dt><dd>{s.detectorVersion}</dd></div></dl></section>
  <section><h3 className="text-xs font-semibold mb-2">Review and reservation</h3><div className="text-xs grid gap-2"><div className="flex justify-between"><span className="funding-muted">Operational state</span><span>{label(s.operationalState)}</span></div><div className="flex justify-between"><span className="funding-muted">Financial review</span><span>{label(s.financialReviewState)}</span></div><div className="flex justify-between"><span className="funding-muted">Reservation</span><span>{label(s.reservation?.status)}</span></div><div className="flex justify-between"><span className="funding-muted">Device / actor</span><span>{s.extensionDeviceId||'Web'} · {s.actorUserId}</span></div></div></section>
  <section><h3 className="text-xs font-semibold mb-2">Event timeline</h3><ol className="border-l border-[#cfd6de] ml-1.5">{(s.events||[]).map((e:any)=><li key={e.id} className="relative pl-4 pb-4 text-xs"><span className="absolute -left-[4px] top-1 w-[7px] h-[7px] rounded-full bg-[#0064e0]"/><div className="font-semibold">{label(e.eventType)}</div><div className="funding-muted">{new Date(e.createdAt).toLocaleString()} · event {e.sequence}</div>{e.metadataJson&&Object.keys(e.metadataJson).length>0&&<dl className="mt-1 bg-[#f5f6f7] p-2 rounded-[5px]">{Object.entries(e.metadataJson).map(([k,v])=><div className="flex justify-between gap-3" key={k}><dt className="funding-muted">{label(k)}</dt><dd className="text-right break-all">{String(v)}</dd></div>)}</dl>}</li>)}</ol></section>
  <div className="p-3 bg-amber-50 text-amber-900 text-xs rounded-[5px]">Confirmation records finance review only. It does not post a ledger entry.</div>
 </div>}</aside></>;
};
