export enum MoneyStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  ALLOCATED = 'ALLOCATED',
  SPENT = 'SPENT',
  LOCKED = 'LOCKED',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
  TRANSFERRED = 'TRANSFERRED',
  RECEIVABLE = 'RECEIVABLE',
  PAYABLE = 'PAYABLE',
  ADJUSTED = 'ADJUSTED'
}

export enum FundOwnerType {
  CLIENT = 'CLIENT',
  AGENCY = 'AGENCY',
  VENDOR = 'VENDOR',
  COMPANY = 'COMPANY'
}

export enum TransactionType {
  CLIENT_PAYMENT = 'CLIENT_PAYMENT',
  CLIENT_WALLET_CREDIT = 'CLIENT_WALLET_CREDIT',
  CLIENT_CAMPAIGN_ALLOCATION = 'CLIENT_CAMPAIGN_ALLOCATION',
  CLIENT_LEFTOVER_SWEEP = 'CLIENT_LEFTOVER_SWEEP',
  CLIENT_REFUND = 'CLIENT_REFUND',
  VENDOR_FUNDING_RECEIPT = 'VENDOR_FUNDING_RECEIPT',
  VENDOR_REPAYMENT = 'VENDOR_REPAYMENT',
  VENDOR_OVERPAYMENT_RECEIVABLE = 'VENDOR_OVERPAYMENT_RECEIVABLE',
  VENDOR_RECEIVABLE_SETTLEMENT = 'VENDOR_RECEIVABLE_SETTLEMENT',
  AGENCY_POOL_CREDIT = 'AGENCY_POOL_CREDIT',
  AGENCY_ALLOCATION = 'AGENCY_ALLOCATION',
  AD_SPEND_CONSUMPTION = 'AD_SPEND_CONSUMPTION',
  FUND_LOCK = 'FUND_LOCK',
  FUND_UNLOCK = 'FUND_UNLOCK',
  MANUAL_JOURNAL_ADJUSTMENT = 'MANUAL_JOURNAL_ADJUSTMENT',
  CORRECTION_REVERSAL = 'CORRECTION_REVERSAL'
}

export enum EntryType {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT'
}

export enum AdAccountNormalizedStatus {
  ACTIVE = 'ACTIVE',
  RESTRICTED = 'RESTRICTED',
  DISABLED = 'DISABLED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  UNSETTLED = 'UNSETTLED',
  ARCHIVED = 'ARCHIVED',
  UNKNOWN = 'UNKNOWN'
}

export enum AlertSeverity {
  CRITICAL = 'CRITICAL',
  WARNING = 'WARNING',
  INFO = 'INFO'
}

export enum AlertStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED'
}

export enum UserRole {
  ADMIN = 'ADMIN',
  FINANCE = 'FINANCE',
  ADS_MANAGER = 'ADS_MANAGER',
  VIEWER = 'VIEWER'
}

export enum LeftoverResolutionAction {
  RETURN_TO_WALLET = 'RETURN_TO_WALLET',
  ALLOCATE_TO_NEW_JOB = 'ALLOCATE_TO_NEW_JOB',
  INITIATE_REFUND = 'INITIATE_REFUND',
  AUTHORIZED_TRANSFER = 'AUTHORIZED_TRANSFER'
}

export enum ReconciliationStatus {
  MATCHED = 'MATCHED',
  DISCREPANCY = 'DISCREPANCY',
  UNRESOLVED = 'UNRESOLVED',
  RESOLVED = 'RESOLVED'
}

export enum FundingRequestStatus {
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  READY = 'READY',
  USED = 'USED',
  CANCELLED = 'CANCELLED'
}

export enum TopupFundingSourceType {
  FUNDING_REQUEST = 'FUNDING_REQUEST',
  FUND_LOT = 'FUND_LOT'
}

export enum TopupConfidence {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  BLOCKED = 'BLOCKED'
}

export enum TopupOperationalState {
  DETECTED = 'DETECTED',
  MAPPED = 'MAPPED',
  UI_OBSERVED = 'UI_OBSERVED',
  REVIEW_REQUIRED = 'REVIEW_REQUIRED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED'
}

export enum FinancialReviewState {
  UNVERIFIED = 'UNVERIFIED',
  CONFIRMED = 'CONFIRMED',
  REJECTED = 'REJECTED'
}

export enum TopupReservationStatus {
  ACTIVE = 'ACTIVE',
  CONFIRMED = 'CONFIRMED',
  RELEASED = 'RELEASED',
  EXPIRED = 'EXPIRED'
}
